### PR TITLE
Add CGI assets

### PR DESCRIPTION
**Pull request by savchenko**
Logo plus square and rounded icons.

- Minor fine-tuning.
- Ribbon is present throughout.
- Exported in most common resolutions.

Closes https://github.com/taskchampion/taskchampion/issues/207

### CODE REVIEW

**Review by djmitche — COMMENTED** [review]
Looks good!

What is "CGI" in this context?

Also, would it make sense to include the vector source? And if scripted, a means for creating the PNGs from the vector?

**Comment by savchenko** [comment]
> Looks good!
> 
> What is "CGI" in this context?
> 
> Also, would it make sense to include the vector source? And if scripted, a means for creating the PNGs from the vector?

ComputerGeneratedGraphics (CGI).

Will share the source vectors in chat. Creating SVG of a civilized size would be a non-trivial exercise due to some of the effects used.

**Comment by djmitche** [comment]
Are those source vectors something we can't distribute?  If they're super-sized, maybe another repo would be appropriate.  I've been caught out in other projects (buildbot) by not having originals for logos and having to reconstruct them by hand.

**Comment by savchenko** [comment]
> Are those source vectors something we can't distribute? If they're super-sized, maybe another repo would be appropriate. I've been caught out in other projects (buildbot) by not having originals for logos and having to reconstruct them by hand.

We probably can, but they are created in proprietary software and are ~3mb blobs in total. I have sent both in chat.

**Comment by dbr** [comment]
Although the file size isn't huge, given:
1. we don't necessarily need all these sizes/variants (some might be only useful in, say, a phone application which would most certainly be a separate project/repo)
2. we might need some additional specific sizes or formats
3. there might be tweaks needed to the icons (which would involve recreating them all)
4. git doesn't allow things to be removed from history

..then I'd be tempted to put these all in a separate taskchampion-graphics repo

If we do that, I think it's good to include the source files in the same repo (even if it is in a proprietary format)

**Comment by savchenko** [comment]
All assets including the source files are uploaded to https://github.com/taskchampion/visuals

I can't update TC organisation icon though. @djmitche , I would recommend using `icon_square_512.png` for it.

**Comment by dbr** [comment]
I'd possibly suggest prefixing the repo with `taskchampion-` to avoid `git clone` or forks outside of TC'c org giving a folder just called `visuals`, but I don't have a strong opinion on that. Aside from that, looks good to me!

**Comment by djmitche** [comment]
> I can't update TC organisation icon though. @djmitche , I would recommend using `icon_square_512.png` for it.

Done!

**Pull request merged**
