### PR TITLE
Tidy up actions names

### PR DESCRIPTION
**Pull request by dbr**

### CODE REVIEW

**Comment by dbr** [comment]
So I think this is about as good as I can get it. Only main weirdness is the "Clippy Results" thing which produces the inline-annotations (from https://github.com/actions-rs/clippy-check ) seems to appear under a random section and there's no obvious way to control this

**Comment by dbr** [comment]
Ah the weirdness is a known bug, https://github.com/actions-rs/clippy-check/issues/45

**Review by djmitche — APPROVED** [review]
Looks good.  Maybe we can also remove "Test - " from the test actions?  This is also fine by me as-it-is.

**Comment by djmitche** [comment]
Did you want to merge this?

**Comment by dbr** [comment]
Woops, yep! Thanks for the reminder

**Pull request merged**
