### PR TITLE
use strum_macros::Display to display Status

### LINKED ISSUE #318: match values of `status` to those in TaskWarrior
TW uses `pending`, `completed', etc.  TC is using single-letter abbreviations.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #318.

### CODE REVIEW

**Comment by dbr** [comment]
It seems accident prone to give access to out both `"Pending"` and `"pending"` in somewhat similar methods (Display impl and `to_taskmap`), especially given

```rust
assert_eq!(Status::from_taskmap("something-else"), Status::Pending);
```

..which presumably means `Status::from_taskmap("completed") != Status::from_taskmap("Completed")` (and one of those becomes `Pending`)

Possibly just `from_taskmap` should return a `Result::Err`, or does that cause other problems?

**Comment by djmitche** [comment]
The idea here is that no taskdb can be "invalid" in the sense that the app completely fails to function, so `from_taskmap` should always succeed.  In practice, we're likely to see this on import from old taskwarrior DB's, where for example a status might be "waiting" (even though that status was dropped in TW 2.6.0).

Is there a specific case where you can see this accident occurring?

**Comment by djmitche** [comment]
@dbr ^^ thoughts?

**Comment by dbr** [comment]
> Is there a specific case where you can see this accident occurring?

The migration from other tools or older versions seems like the most likely - and also if people are using the API to write custom importers, it might be hard to spot that most ticket status translate correctly but the occasional imported `wontfix` status items end up `Pending`

Would it make sense to add some kind of `Status::Unknown` variant to handle these? (maybe even `Status::Unknown(String)`) - that way the parsing can always succeed, but still treat unexpected values distinct from actually-"Pending" ones

**Comment by djmitche** [comment]
Yeah, that makes sense.  We might add more statuses eventually, so that would be a good forward-compatibility change.

**Comment by djmitche** [comment]
@dbr, want to take another look?

**Review by dbr — APPROVED** [review]
LGTM!

**Pull request merged**
