### PR TITLE
produce Tag instances in the parser

### LINKED ISSUE #111: Parse CLI args as Tag earlier
In `crate::argparse::args`, `plus_tag` and `minus_tag` should both return a `Tag`.  Then, Filter and Modify should handle those as already-parsed values.  Currently tags are maintained as strings until `invocation`, at which point it's kind of too late to handle any errors converting from String to Tag.

This is a good internal-refactor issue.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #111

### CODE REVIEW

**Review by dbr — APPROVED** [review]
The clippy lint seems reasonable thing to fix, but otherwise looks good to merge I think!

**Comment by djmitche** [comment]
(rebased and updated)

**Comment by djmitche** [comment]
Hm, I don't know why the docs are failing..

**Comment by dbr** [comment]
That is very odd.

I printed out `stdin` inside the usage-docs command and it looks pretty reasonable - if I cull all the docs content so it's short, it just says something like:

```json
[{"root":"/Users/dbr/code/taskchampion/docs","config":{"book":{"authors":["Dustin J. Mitchell"],"language":"en","multilingual":false,"src":"src","title":"TaskChampion"},"output":{"html":{"default-theme":"ayu"}},"preprocessor":{"usage-docs":{"command":"target/debug/usage-docs"}}},"renderer":"html","mdbook_version":"0.4.9"},{"sections":[]}]
```

..which is all in order

Ah, I think it's a bug in mdbook 0.4.8 (version in TC's Cargo.lock) - if I update to 0.4.9 it seems happy again

This change likely fixed it: https://github.com/rust-lang/mdBook/compare/7e01cf9...d325c60#diff-030bbc3b81baed9210053c583963f03bdcbcd802c2f065254400ffe6266306d6L233

**Comment by djmitche** [comment]
I'll squash this if it's green.

**Pull request merged**
